version: "3.5"
services:
  web:
    image: l3iggs/gollum
    container_name: knowledge-base
    expose:
     - "80"
    volumes:
     - ./knowledge-base:/wiki
    environment:
     - WIKI_USER=john
     - WIKI_PASS=letmein
     - VIRTUAL_HOST=wiki.example.com
     - VIRTUAL_PORT=80
     - LETSENCRYPT_HOST=wiki.example.com
     - LETSENCRYPT_EMAIL=your@email.com
networks:
  default:
    external:
      name: webproxy
